name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with the branch you use for deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set the working directory to 'Personal Portfolio'
      - name: Change working directory
        run: cd "Personal Portfolio"

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Match the version used in your project

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          cd "Personal Portfolio"
          npm install
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Personal Portfolio/dist
