name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies and build the project
      - name: Install and Build
        run: |
          cd "Personal Portfolio"
          npm install
          npm run build

      # Step 4: List built files for debugging
      - name: List Build Directory
        run: ls -la "Personal Portfolio/dist"
      - name: List Actions Directory
        run: ls -la /home/runner/actions_github_pages_*


      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Personal Portfolio/dist
          force_orphan: true


      # Step 6: Debug deployment directory (optional)
      - name: Verify Deployment Directory
        run: ls -la /home/runner/actions_github_pages_1732608562168
