name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Debug the directory structure
      - name: Debug Repository Structure
        run: ls -la

      # Set up Node.js (use a compatible version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Upgrade to Node.js 18 or later

      # Install dependencies and build
      - name: Install dependencies and build
        run: |
          cd "Personal Portfolio" # Use the correct directory name here
          npm install
          npm run build

      # List build output
      - name: List build output
        run: |
          cd "Personal Portfolio/dist" # Use the correct path to the `dist` folder
          ls -la

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Personal Portfolio/dist
          force_orphan: true
