name: GitHub Pages Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install
      working-directory: "Personal Portfolio"  # Set to the directory containing package.json

    - name: Build Project
      run: npm run build
      working-directory: "Personal Portfolio"  # Ensure the build command runs in the correct directory

    - name: Upload to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        build_dir: "./Personal Portfolio/build"  # Adjust to the build output directory within "Personal Portfolio"
